project_id = "lfkmsycadsttrxuoajzk"

[functions.security]
verify_jwt = false

[functions.backup]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.supplier-sync]
verify_jwt = false